export const GET_RESTAURANT = "GET_RESTAURANT";
<<<<<<< HEAD
export const GET_SPECIFIC_RESTAURANT = "GET_SPECIFIC_RESTAURANT";
=======
export const GET_SPECIFIC_RESTAURANT = "GET_SPECIFIC_RESTAURANT";
>>>>>>> 7460fece9fba6aeb9c662dc8843d90d77211f46e
